### ISSUE TITLE
error de matches

### ISSUE THREAD

**Issue by otgo** [lenguaje-latino/latino#100]
Le probé quitando el len == 0 que mande nulo y mira lo que pasa al hacer esto:

latino> cadena.match("vdsv", "(.*)")
[["vdsv", "vdsv"], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""], ["", ""]]

**Comment by primitivorm** [comment]
se corrige error en matches
