### ISSUE TITLE
error Linea 5, 16: error de sintaxis, ',' inesperado en archivo test.lat.

### ISSUE THREAD

**Issue by otgo** [lenguaje-latino/latino#102]
``` 
 1 funcion leche(a)
 2         si a
 3                 retornar "ok"
 4         fin
 5 retornar (falso, "test")
 6 fin
 7
 8 imprimir(leche())
 9
```

**Comment by primitivorm** [comment]
@jarriztg :

Para devolver mas de un valor en una funcion, puedes usar una lista. Solo cambia '(' por '['

 funcion leche(a)
   si a
     retornar "ok"
   fin
   retornar [falso, "test"]
 fin
 
 imprimir(leche())
