### ISSUE TITLE
Error al intentar usar una cadena u otro valor como función

### ISSUE THREAD

**Issue by otgo** [lenguaje-latino/latino#113]
No sé si lleve alguna liberación de memoria despúes y eso lo impida:
```
jarriz@jarriz:~/latino$ latino
Latino 0.9.1
Todos los derechos reservados (C) 2015-2017. Latinoamerica
latino> hola = "hola"
latino> hola()
Violación de segmento
```

**Comment by MelvinG24** [comment]
Si lo que quieres hacer es crear una variable llamada **Hola** con un valor de texto en este caso **Hola** por igual, lo que tienes que hacer es poner el comando "escribir(variable)" asi escribir(hola)

aqui un ejemplo, la variable se llamara mensaje

mensaje = "Hola Mundo"
escribir (mensaje)

**Comment by primitivorm** [comment]
se corrige en la version 1.0 de latino:
https://github.com/primitivorm/latino/releases/tag/v1.0
