### ISSUE TITLE
Poner, no imprimir ni escribir

### ISSUE THREAD

**Issue by akercheval** [lenguaje-latino/latino#114]
### Reportando bug
`no escribir en esta area y marcarlo al completar el issue.`

* [ ] <i>Solamente busco ayuda u orientación</i>.
* [ ] <i>Error global, no me deja correr Latino</i>.
* [ ] <i>El error ocurre en una palabra reservada. Por ejemplo: `si` `osi` `sino` (escribir la palabra reservada en detalles)</i>.
* [ ] <i>Es un error en una función específica (escribir la función en detalles)</i>.
* [ ] <i>Es una falla de memoria (memory leak)</i>.
* [ ] <i>El error solo ocurre en el REPL (al ejecutar `latino` sin parámetros)</i>.
* [x] <i>Sugerencia para Latino</i>.

`no escribir en esta area y marcarlo al completar el issue.`

<b>Más detalles</b>:
Acabo de desarollar Latino 0.9.1 y me parece bien interesante - solo es que debería cambiar en [el gitbook introductoria](https://robincoello.gitbooks.io/latino/content/basico.html) para Latino las referencias a `escribir` o `imprimir` a `poner`. Puede ser que estoy equivocado, pero a mí me parece que `escribir` ni `imprimir` ya no existen en los "built-in" para hacer lo que `print` hace en Python, por ejemplo, y solo `poner` lo hace. 
Seguiré usando el lenguaje y ayudaré cuando puedo!

**Comment by otgo** [comment]
Claro, no te preocupes, será añadida nuevamente la función escribir en la próxima versión, más tardar podría salir el otro domingo.

Acerca de la variable `poner()` es por la palabra de `stdio.h` de C, la cúal es `puts()`.

**Comment by otgo** [comment]
Se me olvidó comentar, si quieres ser parte del proyecto te invito a guiarte en las lineas de estandares de programación:
https://github.com/primitivorm/latino/blob/master/CONTRIBUTING.md

Cualquier desarrollador es bienvenido a Latino :)

**Comment by primitivorm** [comment]
se agrega nuevamente las funciones imprimir y escribir en la version 1.0
https://github.com/primitivorm/latino/releases/tag/v1.0
