### ISSUE TITLE
Cambio de palabra "retorno" a "regresar"

### ISSUE THREAD

**Issue by ingSinTitulo** [lenguaje-latino/latino#116]
<i>Sugerencia para Latino</i>.

Se recomienda adoptar la palabra "regresar", debido a que refleja mejor lo que hace esa orden.

**Comment by jordanclic** [comment]
La palabra retorno tiene el mismo significado que return, estaría bien conservar la nomenclatura para poder facilitar el aprendizaje de otros lenguajes.
