### ISSUE TITLE
ent + dec 

### ISSUE THREAD

**Issue by robincoello** [lenguaje-latino/latino#117]
En 
https://github.com/primitivorm/latino/blob/master/ejemplos/04-expresiones.lat

entero + decimal da entero
En los ejemplos dice 
ent + dec = dec
Talvez es un error, o es asi ?

**Comment by primitivorm** [comment]
En que caso te da `entero + decimal da entero`?
Estoy corriendo el script y corre perfecto

**Comment by robincoello** [comment]
te paso el resultado de la ejecucion de, como veras la linea dos deberia dar 11.05, pero solo da 11, etc etc

https://github.com/primitivorm/latino/blob/master/ejemplos/04-expresiones.lat

############## suma ###############
2
11 #a 1 se le suma 10.05 da como resultado 11.05, etc etc 
11
20
############## resta ###############
2
-9
9
10
############## multiplicacion ###############
1
10
10
0
############## division ###############
1
0,1
10
inf
############## modulo ###############
0
1
0
-nan

**Comment by primitivorm** [comment]
Hola Robinson al parecer es el idioma de tu equipo, deberia de estar en español, si tienes otro idioma configurado te recomiendo que descomentes las siguientes lineas del archivo latino.c, se encuentran en el main.

    // setlocale(LC_NUMERIC, "es_MX");
    // setlocale(LC_MONETARY, "es_MX");

Recompilas por favor y me comentas

podrias por favor poner la salida del siguiente comando para estar seguro que es el idioma.
`locale`

Yo tengo lo siguiente:
```
$ locale
LANG=es_MX.utf8
LANGUAGE=es_MX.utf8
LC_CTYPE="es_MX.utf8"
LC_NUMERIC="es_MX.utf8"
LC_TIME="es_MX.utf8"
LC_COLLATE="es_MX.utf8"
LC_MONETARY="es_MX.utf8"
LC_MESSAGES="es_MX.utf8"
LC_PAPER="es_MX.utf8"
LC_NAME="es_MX.utf8"
LC_ADDRESS="es_MX.utf8"
LC_TELEPHONE="es_MX.utf8"
LC_MEASUREMENT="es_MX.utf8"
LC_IDENTIFICATION="es_MX.utf8"
LC_ALL=
```
Saludos

**Comment by robincoello** [comment]
voila 
[robin@localhost .ssh]$ locale
LANG=fr_BE.UTF-8
LC_CTYPE="fr_BE.UTF-8"
LC_NUMERIC="fr_BE.UTF-8"
LC_TIME="fr_BE.UTF-8"
LC_COLLATE="fr_BE.UTF-8"
LC_MONETARY="fr_BE.UTF-8"
LC_MESSAGES="fr_BE.UTF-8"
LC_PAPER="fr_BE.UTF-8"
LC_NAME="fr_BE.UTF-8"
LC_ADDRESS="fr_BE.UTF-8"
LC_TELEPHONE="fr_BE.UTF-8"
LC_MEASUREMENT="fr_BE.UTF-8"
LC_IDENTIFICATION="fr_BE.UTF-8"
LC_ALL=
[robin@localhost .ssh]$

**Comment by robincoello** [comment]
Listo, 
descomentando 

```
 setlocale(LC_NUMERIC, "es_MX");
 setlocale(LC_MONETARY, "es_MX");
```
ahora un 

```
cmake .
make
sudo make install 

```

me da el resultado esperado 

[robin@localhost latino]$ latino ejemplos/04-expresiones.lat 
############## suma ###############
2
11.05
11.05
20.1
############## resta ###############
2
-9.050000000000001
9.050000000000001
10
############## multiplicacion ###############
1
10.05
10.05
5.025
############## division ###############
1
0.09950248756218905
10.05
20.1
############## modulo ###############
0
1
0.05000000000000071
0.05000000000000071

Gracias

**Comment by primitivorm** [comment]
De nada 😃
