### ISSUE TITLE
1er test

### ISSUE THREAD

**Issue by robincoello** [lenguaje-latino/latino#12]

**Comment by robincoello** [comment]
https://huboard.com/primitivorm/latino

**Comment by primitivorm** [comment]
@robincoello no entiendo el error :(

**Comment by robincoello** [comment]
es un test para esto 
https://huboard.com/primitivorm/latino

Date: Fri, 15 Apr 2016 13:23:46 -0700

**Comment by primitivorm** [comment]
ok ok es como trello, cierto?

**Comment by robincoello** [comment]
pero intgrado al github, lo viste que te parece? 

Date: Fri, 15 Apr 2016 13:33:10 -0700

**Comment by primitivorm** [comment]
me parece muy bien hay que cambiarnos a esta plataforma :)

**Comment by robincoello** [comment]
listo cambiada !
