### ISSUE TITLE
poner(diccionario.nulo)

### ISSUE THREAD

**Issue by otgo** [lenguaje-latino/latino#124]
### Reportando bug
`no escribir en esta area y marcarlo al completar el issue.`

* [ ] <i>Solamente busco ayuda u orientación</i>.
* [ ] <i>Error global, no me deja correr Latino</i>.
* [ ] <i>El error ocurre en una palabra reservada. Por ejemplo: `si` `osi` `sino` (escribir la palabra reservada en detalles)</i>.
* [x] <i>Es un error en una función específica (escribir la función en detalles)</i>.
* [ ] <i>Es una falla de memoria (memory leak)</i>.
* [ ] <i>El error solo ocurre en el REPL (al ejecutar `latino` sin parámetros)</i>.
* [ ] <i>Sugerencia para Latino</i>.

`no escribir en esta area y marcarlo al completar el issue.`

<b>Más detalles</b>:
Al poner un diccionario nulo manda un segfault

<b>Código en donde ocurre</b>:
```c
poner(valor.nulo)

Ret: Segmentation fault (core dumped)
```

**Comment by MelvinG24** [comment]
@otgo 
¿Te refieres a hacer algo así?

> carro = {"marca":"Toyota", "modelo":nulo}
> 
> escribir(carro.modelo)
> //Devolverá el valor nulo

**Comment by StunxFS** [comment]
Yo creo que se refiere a un diccionario vacío

**Comment by MelvinG24** [comment]
Si se puede crear un diccionario vacio en Latino, aquí un ejemplo:

``` c
> carro={}
> poner(tipo(carro))           //Devolverá diccionario
```

Ahora bien, si lo que se quiere es crear un diccionario con una propiedad llamada **nulo**, entonces ahi si que no se puede, ya que **nulo** es una palabra reservada.
