### ISSUE TITLE
Operador u #array #string

### ISSUE THREAD

**Issue by otgo** [lenguaje-latino/latino#125]
### Reportando bug
`no escribir en esta area y marcarlo al completar el issue.`

* [ ] <i>Solamente busco ayuda u orientación</i>.
* [ ] <i>Error global, no me deja correr Latino</i>.
* [ ] <i>El error ocurre en una palabra reservada. Por ejemplo: `si` `osi` `sino` (escribir la palabra reservada en detalles)</i>.
* [ ] <i>Es un error en una función específica (escribir la función en detalles)</i>.
* [ ] <i>Es una falla de memoria (memory leak)</i>.
* [ ] <i>El error solo ocurre en el REPL (al ejecutar `latino` sin parámetros)</i>.
* [x] <i>Sugerencia para Latino</i>.

`no escribir en esta area y marcarlo al completar el issue.`

<b>Más detalles</b>:
Añadir operador para obtener el tamaño de una cadena o diccionario

<b>Código</b>:
```c
elementos = [1, 2, 3]
poner(#elementos) /* ret: 3 */
mi_cadena = "hola"
poner(#mi_cadena) /* ret; 4 */
```

**Comment by MelvinG24** [comment]
@otgo 
¿No se si te referiras a esto?

> persona = {
>     "nombre":"Melvin",
>     "apellido":"Guerrero",
>     "edad":50,
>     "etimología":"Latino"
> }
> escribir(dic.longitud(persona)) 
> //Devolverá un valor de 4
