### ISSUE TITLE
Error al obtener tamaño lista

### ISSUE THREAD

**Issue by otgo** [lenguaje-latino/latino#126]
### Reportando bug
`no escribir en esta area y marcarlo al completar el issue.`

* [ ] <i>Solamente busco ayuda u orientación</i>.
* [x] <i>Error global, no me deja correr Latino</i>.
* [ ] <i>El error ocurre en una palabra reservada. Por ejemplo: `si` `osi` `sino` (escribir la palabra reservada en detalles)</i>.
* [x] <i>Es un error en una función específica (escribir la función en detalles)</i>.
* [ ] <i>Es una falla de memoria (memory leak)</i>.
* [ ] <i>El error solo ocurre en el REPL (al ejecutar `latino` sin parámetros)</i>.
* [ ] <i>Sugerencia para Latino</i>.

`no escribir en esta area y marcarlo al completar el issue.`

<b>Más detalles</b>:
Será un error de Latino o en mi código que genera ese seg. default?

El error está en la función `dic.longitud()`

<b>Código en donde ocurre</b>:
```c
 datos = {
    "gane" : "100 MXN",
    "gaste" : "90 MXN",
    "tengo" : "10 MXN",
    "manzanas":{
        "tengo" : 10,
        "colores":[
            "verdes",
            "rojas"
        ]
    }
}
poner("Ganamos " .. datos.gane)
poner("Gastamos " .. datos.gaste)
poner("Y nos quedan " .. datos.tengo)
poner("De manzanas, tenemos " .. datos.manzanas.tengo)
poner("LONGITUD: ".. dic.longitud(datos.manzanas)) // No manda error, ret: 2
poner("LONGITUD: ".. dic.longitud(datos.manzanas.colores)) // Error: con lista [ elementos ]
// Código no continúa aquí
desde (i=0; i<dic.longitud(datos.manzanas.colores); i++)
   //  poner("Color "..i..": "..datos.manzanas.colores[i])
   poner(i)
fin
```

Retorno: Segmentation fault (core dumped)

**Comment by primitivorm** [comment]
cambialo por:
desde (i=0; i<datos.manzanas.colores.longitud(); i++)
   //  poner("Color "..i..": "..datos.manzanas.colores[i])
   poner(i)
fin
