### ISSUE TITLE
Añadir diccionario.funcion()

### ISSUE THREAD

**Issue by otgo** [lenguaje-latino/latino#127]
### Reportando bug
`no escribir en esta area y marcarlo al completar el issue.`

* [ ] <i>Solamente busco ayuda u orientación</i>.
* [ ] <i>Error global, no me deja correr Latino</i>.
* [ ] <i>El error ocurre en una palabra reservada. Por ejemplo: `si` `osi` `sino` (escribir la palabra reservada en detalles)</i>.
* [ ] <i>Es un error en una función específica (escribir la función en detalles)</i>.
* [ ] <i>Es una falla de memoria (memory leak)</i>.
* [ ] <i>El error solo ocurre en el REPL (al ejecutar `latino` sin parámetros)</i>.
* [x] <i>Sugerencia para Latino</i>.

`no escribir en esta area y marcarlo al completar el issue.`

<b>Más detalles</b>:
Poder añadir una función a un diccionario también de manera directa, usando palabra reservada: `funcion`

<b>Ejemplo</b>:
```c
funs = {}
funcion funs.esc(a)
    poner(a)
fin
```

**Comment by MelvinG24** [comment]
@otgo 
¿podrías dar otro ejemplo del código que propones?

Los diccionarios en latino pueden almacenar métodos, aquí te paso la documentación:
https://manual-latino.readthedocs.io/es/latest/sintaxis/Diccionarios.html#metodos-de-un-diccionario

¿No se si es a esto a lo que te refieres?
