### ISSUE TITLE
Devolver error al usar: global diccionario.variable = xx

### ISSUE THREAD

**Issue by otgo** [lenguaje-latino/latino#128]
### Reportando bug
`no escribir en esta area y marcarlo al completar el issue.`

* [ ] <i>Solamente busco ayuda u orientación</i>.
* [ ] <i>Error global, no me deja correr Latino</i>.
* [ ] <i>El error ocurre en una palabra reservada. Por ejemplo: `si` `osi` `sino` (escribir la palabra reservada en detalles)</i>.
* [ ] <i>Es un error en una función específica (escribir la función en detalles)</i>.
* [ ] <i>Es una falla de memoria (memory leak)</i>.
* [ ] <i>El error solo ocurre en el REPL (al ejecutar `latino` sin parámetros)</i>.
* [x] <i>Sugerencia para Latino</i>.

`no escribir en esta area y marcarlo al completar el issue.`

<b>Más detalles</b>:
Devolver error al usar: global diccionario.variable = nulo

<b>Ejemplo</b>:
```c
a = {}
global a.b = 5 // marcar error, se intenta generar una global desde un array, podría causar conflictos
```

**Comment by MelvinG24** [comment]
@otgo 
¿Cual versión de latino usaste para ese ejemplo?

Estoy utilizando la versión de latino 1.2.0 y me funciona, aquí una captura de pantalla:

![global](https://user-images.githubusercontent.com/23342477/86964785-9e81fa80-c134-11ea-8839-2da8c4ed689f.png)
