### ISSUE TITLE
No se como usarlo xD

### ISSUE THREAD

**Issue by otgo** [lenguaje-latino/latino#13]
tengo un vps de ovh (linux ubuntu) y no se ni como usarlo y que linux lo arranque :dizzy_face: 
quiero crear un bot de telegram en tu lenguaje y crear el repositorio de dicho bot y explicar compilarlo, me podrías explicar?

**Comment by primitivorm** [comment]
Hola @jarriztg:

Para compilarlo en linux es con los siguientes comandos:
$git clone https://github.com/primitivorm/latino
$cd latino
$cmake .
$make
$sudo make install

Luego puedes correr tu script latino desde consola con:
$latino nombre_archivo.lat

O puedes correr el interprete de latino con:
$latino

Los ejemplos basicos de como usarlo los encuentras en:
https://github.com/primitivorm/latino/tree/master/ejemplos

Aqui te dejo un video de como extender las funciones de latino por si requieres alguna funcionalidad en particular:
https://www.youtube.com/watch?v=TNh5FYq8Tfk

Si gustas te puedo ayudar a implementarla, solo necesito una idea mas clara de que requieres hacer.

Quedo a tus ordenes
Saludos

**Comment by otgo** [comment]
Me parece magnifico que me ayudes a implementar esto
Mira el repositorio en bash que es
http://github.com/iicc1/TgBash

Registrate en la red social Telegram
http://telegram.org

Lo que hacen los bots son funciones como buscar mapas, buscar música, compras en amazon, busquedas de google, moderar un grupo automaticamente, es una idea genial crearlo en tu lenguaje de programación ya que me gusta como está interpretado y más que nada porque me gustaría que sea un lenguaje de uso así como python, lua, bash, etc

http://api.telegram.org/bots/core
Mira ahí, la idea es obtener los datos de la página y que el bot obtenga el mensaje del usuario atraves de /getUpdates

Lo cual hace que obtengas las actualizaciones en cadenas de datos, y decodificarlas con un json o cortando el texto. Si quieres registrate en telegram y nos ponemos en contacto en el sig link http://telegram.me/jarriz :)

**Comment by flickerapps** [comment]
Buenisima idea @jarriztg  ! Me apunto para cualquier colaboracion
