### ISSUE TITLE
REPL: 512:7666008

### ISSUE THREAD

**Issue by JRXYZ** [lenguaje-latino/latino#133]
### Reportando bug
`no escribir en esta area y marcarlo al completar el issue.`

* [ ] <i>Solamente busco ayuda u orientación</i>.
* [x] <i>Error global, no me deja correr Latino</i>.
* [ ] <i>El error ocurre en una palabra reservada. Por ejemplo: `si` `osi` `sino` (escribir la palabra reservada en detalles)</i>.
* [ ] <i>Es un error en una función específica (escribir la función en detalles)</i>.
* [ ] <i>Es una falla de memoria (memory leak)</i>.
* [ ] <i>El error solo ocurre en el REPL (al ejecutar `latino` sin parámetros)</i>.
* [ ] <i>Sugerencia para Latino</i>.

`no escribir en esta area y marcarlo al completar el issue.`

<b>Más detalles</b>:

<b>Código en donde ocurre</b>:
```c
// pegar tu código aquí

```

**Comment by JRXYZ** [comment]
Buenas quisiera saber a que se debe este error.

![image](https://user-images.githubusercontent.com/8475565/80835736-fcd0b100-8bb8-11ea-9d93-e7d9d22da530.png)

**Comment by StunxFS** [comment]
Creo que este repositorio ya no recibe actualizaciones, pero este sí: https://github.com/MelvinG24/Latino.
Latino ya va por la versión 1.2.0

**Comment by MelvinG24** [comment]
@JRXYZ, como dice @StunxFS , ese error ya fue solucionado en la nueva version de Latino 1.2.0.
Dicho lo anterior, procederé a cerrar este issue
