### ISSUE TITLE
diccionarios

### ISSUE THREAD

**Issue by otgo** [lenguaje-latino/latino#14]
root@vps273405:~# latino 24-diccionarios.lat
Error: Linea 3: error de sintaxis, ',' inesperado, se esperaba '}'

**Comment by robincoello** [comment]
Puedes poner el codigo q usaste ?

**Comment by otgo** [comment]
es el de fuente

**Comment by aluzardo** [comment]
Este código es el que falla? https://github.com/primitivorm/latino/blob/master/ejemplos/24-diccionarios.lat

```
vacio = {}
dic = { "Chilindrina": "Maria Antonieta de las Nieves",
     "El chavo del 8": "Roberto Gomez Bolaños",
     "Tres patines": "Leopoldo Fernandez" }

escribir(vacio)
```

**Comment by primitivorm** [comment]
@aluzardo muchas gracias por levantar el issue, estamos trabajando en la correccion

Saludos
