### ISSUE TITLE
Manejo de referencias

### ISSUE THREAD

**Issue by StunxFS** [lenguaje-latino/latino#152]
¡Hola :D!
Me gustaría que las referencias se implementasen en Latino. Esto se podría hacer implementando un keyword (palabra reservada)  como el ``ref`` de C#.

Ejemplo:
```cs
void swap(ref int a, ref int b) {
    int aux = a;
    a = b; b = aux;
}
// uso:
int a = 100; int b = 200;
swap(ref a, ref b);
```

En Latino sería algo así:
```latino
funcion swap(ref a, ref b)
    aux = a
    a = b
    b = aux
fin

a, b = 100, 200
swap(ref a, ref b)
```
¿Qué tal?

**Comment by MelvinG24** [comment]
Que tal @StunxFS,

Me disculpo por no haber respondido antes. Estaba mirando tu sugerencia y veo que eso es algo que ya se puede hacer en Latino.

```c
funcion swap(a, b)
    aux = a
    a = b
    b = aux
fin

a, b = 100, 200
swap(a, b)
```

amenos que no este entendiendo del todo lo que propones si puedes dar otro ejemplo
