### ISSUE TITLE
GitHub Patrocinadores? (GitHub Sponsors?)

### ISSUE THREAD

**Issue by ChannelJuanNews** [lenguaje-latino/latino#180]
### Feature

Seria posible activar GitHub patrocinadores en la organización de lenguaje latino?

**Comment by MelvinG24** [comment]
Por supuesto, ya me encargaré de activarlo, muchas gracias por la sugerencia <3

**Comment by MelvinG24** [comment]
Ya se está trabajando para poder recibir donaciones en GitHub, solo se está esperando a finalizar la registración de Latino como fundación
