### ISSUE TITLE
Key press, o -t para que se cierre la ventana de latino

### ISSUE THREAD

**Issue by Marcelito444** [lenguaje-latino/latino#189]
He instalado el latino pero al ejecutar un archivo .lat desde el explorador de windows, este se ejecuta y se cierra inmediatamente sin poder apreciar el resultado. Se necesita una opción (o quizas ya existe) para que haya un tiempo de espera o una espera de una tecla para que se cierre.
### Reportando bug
`no escribir en esta área y marcarlo al completar el issue.`

* [ ] <i>Solamente busco ayuda u orientación</i>.
* [x] <i>Sugerencia para Latino</i>.

`no escribir en esta área y marcarlo al completar el issue.`

<b>Más detalles</b>:

<b>Código en donde ocurre</b>:
```c
// código_aquí

```

**Comment by jorge2985** [comment]
Buenas noches @Marcelito444 ¿Podrás pasarme una captura de lo que te sucede? Tengo entendido que no debiera suceder lo que comentas, o tal vez estoy entendiendo mal.

**Comment by primitivorm** [comment]
hola @Marcelito444 puedes usar la funcion sis.dormir(5) y pasandole el numero de segundos que quieres que se espere o con la funcion leer() la cual espera a que el usuario presione una tecla, ej.

```
escribir("hola")
//sis.dormir(5)  // esta es una opcion
escribir("presiona una tecla para terminar")
leer()
```
