### ISSUE TITLE
Request to tag a new release

### ISSUE THREAD

**Issue by nandahkrishna** [lenguaje-latino/latino#190]
(Apologies for opening this issue in English, I do not speak Spanish.)

Could you please tag a new release (perhaps `v1.4.1`)? The `.gitmodules` file was not added in `v1.4.0`, due to which we are unable to build `latino` for [Homebrew](https://brew.sh). Related pull request: Homebrew/homebrew-core#75202. Thank you!

**Comment by jorge2985** [comment]
Sorry for late reply, I'll send the request to responsible for compilation @primitivorm 
Did you check https://github.com/lenguaje-latino/latino-core?

**Comment by nandahkrishna** [comment]
Thank you for your response, @jorge2985. Yes, I did take a look at `latino-core` but I didn't raise an issue there. Since we build the whole `latino` project, I thought it would be best to raise the issue here (since it's happening because `1.4.0` doesn't have the `.gitmodules` file).

I'll open an issue there if you think that's a good option.

**Comment by jorge2985** [comment]
Hi @nandahkrishna I was referring to the `.gitmodules` file. You can find it in `latino-core`. However I found the file in both places:

- https://github.com/lenguaje-latino/latino/blob/master/.gitmodules
- https://github.com/lenguaje-latino/latino-core/blob/main/.gitmodules

Please let me know if it's what you need.

**Comment by nandahkrishna** [comment]
@jorge2985 both repositories need their own `.gitmodules` files:

* `lenguaje-latino/latino` for its own submodule (`latino-core` is the submodule).
* `lenguaje-latino/latino-core` requires this for the `latino-regex` submodule.

We need the `.gitmodules` file to be available in a tagged release. In `v1.4.0` (https://github.com/lenguaje-latino/latino/tree/v1.4.0) you can see that there is no `.gitmodules` file. So we are not able to pull all submodules to build `latino` from source.

We (at Homebrew) only ship stable releases so we cannot build using `master`. So it would be helpful if this repository, `lenguaje-latino/latino` had a new tagged release (for example, `v1.4.1`) to fix the issue.

**Comment by primitivorm** [comment]
Hola @nandahkrishna se ha creado la versión 1.4.1, esperando que con esto se corrija el error

**Comment by nandahkrishna** [comment]
Gracias, @primitivorm!

**Comment by nandahkrishna** [comment]
I will close this issue now, and report if there are any other errors. Thank you very much!

(Homebrew PR for `latino 1.4.1` is open: Homebrew/homebrew-core#77686)
