### ISSUE TITLE
Instalación en manjaro 

### ISSUE THREAD

**Issue by 64sys** [lenguaje-latino/latino#191]
Hola, estoy intentando instlar latino en manjaro pero no funciona.  descargue el .zip de la version 1.4 porque en la "receta" para instalar descargando desde "sudo git clone https://github.com/lenguaje-latino/latino-core" no existe el ./gcc_compilar.sh
Intento:
make
devuelve: *** No se especificó ningún objetivo y no se encontró ningún makefile.  Alto.

Gracias.

**Comment by 64sys** [comment]
latino-1.4.0]$ sh ./configure
fatal: no es un repositorio git (ni ninguno de los directorios superiores): .git
./configure: línea 2: ./tools/fix: No existe el fichero o el directorio
-- 
.__          __  .__
|  | _____ _/  |_|__| ____   ____
|  | \__  \   __\   |/    \ /  _ \
|  |__/ __ \|  | |  |   |  (  <_> )
|____(____  /__| |__|___|  /\____/
          \/             \/
-- ..............................................
-- >>>>>>   Latino 
-- ..............................................
-- Generador .............. Unix Makefiles
-- Tipo de Build .......... Debug
CMake Error at cmake/Modules/GetLatVersion.cmake:1 (file):
  file failed to open for reading (No such file or directory):

    /home/mock/latino-1.4.0/latino-core/include/latino.h
Call Stack (most recent call first):
  CMakeLists.txt:39 (include)


-- Latino Version ......... ...0
-- LAT_EJEMPLOS ........... OFF
CMake Error at CMakeLists.txt:47 (add_subdirectory):
  add_subdirectory given source "latino-core/src" which is not an existing
  directory.


-- Configuring incomplete, errors occurred!
See also "/home/mock/latino-1.4.0/CMakeFiles/CMakeOutput.log".
make: *** No se especificó ningún objetivo y no se encontró ningún makefile.  Alto.

**Comment by primitivorm** [comment]
hola @belmotek, puedes intentar correr el siguiente comando:

`git submodule update --init --recursive`

posteriormente:

```
cmake .
make
sudo make install
```

**Comment by MelvinG24** [comment]
Hola @belmotek 
Aqui te dejo donde esta resuelto este problema en Manjaro Linux.
link aqui:
https://github.com/lenguaje-latino/latino/issues/178#issuecomment-792331008

**Comment by MelvinG24** [comment]
Este post al ser un duplicado y estar inactivo se procede a ser cerrado. Si en caso que el error no se alla solucionado este sera re-abierto.
