### ISSUE TITLE
No se ve el ícono de Latino

### ISSUE THREAD

**Issue by jorge2985** [lenguaje-latino/latino#196]
### Reportando bug
`no escribir en esta área y marcarlo al completar el issue.`

* [X] <i>Icono de Latino no aparece en el ejecutable ni en los archivos</i>.
* [ ] <i>Error global, no me deja correr Latino</i>.
* [ ] <i>Error global, no me deja correr Latino</i>.
* [ ] <i>El error ocurre en una palabra reservada. Por ejemplo: `si` `osi` `sino` (escribir la palabra reservada en detalles)</i>.
* [ ] <i>Es un error en una función específica (escribir la función en detalles)</i>.
* [ ] <i>Es una falla de memoria (memory leak)</i>.
* [ ] <i>El error solo ocurre en el REPL (al ejecutar `latino` sin parámetros)</i>.

`no escribir en esta área y marcarlo al completar el issue.`

<b>Más detalles</b>:
Luego de instalar Latino el icono y el archivo ejecutable están separados, eso hace que no se vea el icono de Latino en el ejecutable ni en los archivos .lat

<b>Código en donde ocurre</b>:
```c
// código_aquí

```

**Comment by MelvinG24** [comment]
Tiene que anexar el archivo de resource.ms a la solucion de VS en Windows antes de compilar.

El archivo de resource.ms  se encuentra en "latino/latino-core/src/vs_resources"

**Comment by jorge2985** [comment]
Me refiero a Latino después de instalarlo, sin que se tenga que compilar. A menos que se tenga que hacer previo a la creación del instalador.

**Comment by MelvinG24** [comment]
Eso se asigna al momento de compilar, no de otra manera. El fallo esta solucionado en el latino-core
