### ISSUE TITLE
Error en ciclo condicional

### ISSUE THREAD

**Issue by jorge2985** [lenguaje-latino/latino#200]
### Reportando bug
`no escribir en esta área y marcarlo al completar el issue.`

* [x] <i>Error global, no me deja correr Latino</i>.
* [ ] <i>El error ocurre en una palabra reservada. Por ejemplo: `si` `osi` `sino` (escribir la palabra reservada en detalles)</i>.
* [x] <i>Es un error en una función específica (escribir la función en detalles)</i>.
* [ ] <i>Es una falla de memoria (memory leak)</i>.
* [ ] <i>El error solo ocurre en el REPL (al ejecutar `latino` sin parámetros)</i>.

`no escribir en esta área y marcarlo al completar el issue.`

<b>Más detalles</b>:

Devuelve `11` y debiera devolver `10`. Sigue sumando el valor de `x` luego de `10`

<b>Código en donde ocurre</b>:
```c
x = 1

repetir
    x = x + 1
hasta (x == 10)

imprimir(x)

```

**Comment by FrkL81** [comment]
No es un error. <---------

El manual de Latino dice que: Esta condicional **_ejecuta su bloque de código al menos una vez_** antes de verificar si su condición es cumplida.

Por lo cual un contador dentro del ciclo siempre sumará su incremento por lo menos una vez. De hecho, si mueves tu instrucción imprimir(x) dentro del ciclo se puede ver como se imprimen los números del 1 al 10 ó del 2 al 11 dependiendo si se coloca antes o después del contador. 

```
limpiar()
x = 1

repetir
    imprimir(x)
    x = x + 1
    #imprimir(x)
hasta (x == 10)

#imprimir(x)
leer()
```

**Comment by jorge2985** [comment]
Cierro el Issue.
