### ISSUE TITLE
Segmentation Fault en for loop

### ISSUE THREAD

**Issue by MarcoTab** [lenguaje-latino/latino#202]
### Reportando bug
`no escribir en esta área y marcarlo al completar el issue.`

* [ ] <i>Error global, no me deja correr Latino</i>.
* [ ] <i>El error ocurre en una palabra reservada. Por ejemplo: `si` `osi` `sino` (escribir la palabra reservada en detalles)</i>.
* [ ] <i>Es un error en una función específica (escribir la función en detalles)</i>.
* [X] <i>Es una falla de memoria (memory leak)</i>.
* [ ] <i>El error solo ocurre en el REPL (al ejecutar `latino` sin parámetros)</i>.

`no escribir en esta área y marcarlo al completar el issue.`

<b>Más detalles</b>:

Salta un Segmentation Fault al usar la funcion lista.longitud a la par con rango para un loop `para`. 
Estoy usando Latino v1.4.0

<b>Código en donde ocurre</b>:
```c
// Funciona
l = [1,2,3,4]
lon = lista.longitud(l)
para i en rango(lon)
    poner(i)
fin

// ...

// No funciona
l = [1,2,3,4]
para i en rango(lista.longitud(l))
    poner(i)
fin
```

**Comment by MelvinG24** [comment]
el comando `para en rango` solo admite valores numéricos y/o variables, pero no expresiones. No es un error, así esta creado

**Comment by MelvinG24** [comment]
en vista de que esto no es un error, paso a cerrar el Issue
