### ISSUE TITLE
Archivo no encontrado: latobj.h

### ISSUE THREAD

**Issue by ulf-frostypaw** [lenguaje-latino/latino#207]
### Reportando bug
`no escribir en esta área y marcarlo al completar el issue.`

* [ - ] <i>Error global, no me deja correr Latino</i>.
* [ ] <i>El error ocurre en una palabra reservada. Por ejemplo: `si` `osi` `sino` (escribir la palabra reservada en detalles)</i>.
* [ ] <i>Es un error en una función específica (escribir la función en detalles)</i>.
* [ ] <i>Es una falla de memoria (memory leak)</i>.
* [ ] <i>El error solo ocurre en el REPL (al ejecutar `latino` sin parámetros)</i>.

`no escribir en esta área y marcarlo al completar el issue.`

<b>Más detalles</b>:
Buenas tardes. Quería probar el lenguaje, con el websocket en mi computadora pero al querer compilarlo me salía un error sobre un archivo no encontrado. Primeramente me salia sobre una libreria de ``` readline/history.h ```. Lo instalé pero me salio el error antes mencionado,

<b>Código en donde ocurre</b>:
```bash
In file included from /usr/local/include/latino.h:55,
                 from /home/ulf-frostypaw/public_html/API_LATINO/src/lat_socket_compat.h:65,
                 from /home/ulf-frostypaw/public_html/API_LATINO/src/latino-socket.c:35:
/usr/local/include/latmv.h:32:10: fatal error: latobj.h: No existe el archivo o el directorio
   32 | #include "latobj.h"
      |          ^~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/latino-socket.dir/build.make:76: CMakeFiles/latino-socket.dir/src/latino-socket.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:83: CMakeFiles/latino-socket.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

```

**Comment by primitivorm** [comment]
Hola @ulf-frostypaw debes de tener instalado latino en tu sistema, valida que tengas la cabecera latobj.h en esta ruta: 
/usr/local/include/

En caso de que no la tengas ejecuta 
sudo make install 
En la ruta donde tienes tu codigo de latino
Ej. cd ~/src/latino
sudo make install 

Con esto tendras todas la cabeceras de latino instaladas en tu sistema linux / unix

**Comment by ulf-frostypaw** [comment]
Je. Gracias, lo probaré .
