### ISSUE TITLE
sis.iraxy() solo funciona 2 veces dentro de un ciclo mientras.

### ISSUE THREAD

**Issue by FrkL81** [lenguaje-latino/latino#208]
### Reportando bug
`no escribir en esta área y marcarlo al completar el issue.`

* [ ] <i>Error global, no me deja correr Latino</i>.
* [ ] <i>El error ocurre en una palabra reservada. Por ejemplo: `si` `osi` `sino` (escribir la palabra reservada en detalles)</i>.
* [ ] <i>Es un error en una función específica (escribir la función en detalles)</i>.
* [ ] <i>Es una falla de memoria (memory leak)</i>.
* [ ] <i>El error solo ocurre en el REPL (al ejecutar `latino` sin parámetros)</i>.

`no escribir en esta área y marcarlo al completar el issue.`

<b>Más detalles</b>:

<b>Código en donde ocurre</b>:
```c
c = 1
sis.iraxy(40,3)
imprimir ("Los numeros del 1 al 99 son:")
fil = 7
col = 5
mientras (c < 100)
    sis.iraxy(col,fil)
    si c < 10
        c = "0"..c
    fin
    imprimir (c)
    c = c + 1
    col = col + 4
    si col > 101
        col = 5
        fil = fil + 2
    fin
fin
leer()
```

**Comment by FrkL81** [comment]
El código debe escribir los números del 1 al 99 controlando la posición de de las filas y las columnas. Se deben generar 4 filas, sin embargo, solo se generan las 2 primeras de forma correcta hasta el numero 50 y de ahí en delante los números se imprimen uno debajo del otro en la primera columna de la consola.

**Comment by FrkL81** [comment]
Saludos, me acabo de percatar de que el error **Solo Ocurre En el Terminal Integrado de Visual Studio Code.**
Si se ejecuta en una terminal externa **Funciona bien.**

GRACIAS por este genial lenguaje de programación.

**Comment by primitivorm** [comment]
Es un error propio del Terminal Integrado de Visual Studio Code
