### ISSUE TITLE
Error: Variable "sumar" indefinida > Latino 0.5.0

### ISSUE THREAD

**Issue by robincoello** [lenguaje-latino/latino#30]
sumar(10,20) > Error: Variable "sumar" indefinida

**Comment by primitivorm** [comment]
Es correcto el error ya que la funcion sumar no es parte de la funciones built-in de Latino, puedes crear la funcion asi:

```
#funcion definida por el usuario
funcion sumar(a,b)
    retorno a+b
fin

resultado = sumar(10, 20)
escribir(resultado)
```

**Comment by robincoello** [comment]
en:  latino/src/vm.h
existe
void lat_sumar(lat_vm\* vm);

**Comment by primitivorm** [comment]
@robincoello `lat_sumar` esta asociada al simbolo `+`, puedes ver el listado de funciones registradas en el metodo:
`lat_crear_maquina_virtual()`  en el archivo vm.c

```
    lat_asignar_contexto_objeto(lat_obtener_contexto(ret), lat_cadena_nueva(ret, "+"), lat_definir_cfuncion(ret, lat_sumar));
```

Esta parte `lat_cadena_nueva(ret, "+")` es la palabra reservada para latino, es decir le estamos diciendo a la maquina virtual, registrame el simbolo + para que ejecute la funcion de c `lat_sumar`
