### ISSUE TITLE
cmd error sistema(variable)

### ISSUE THREAD

**Issue by otgo** [lenguaje-latino/latino#38]
latino test.lat
nodo_tipo:39
nodo_tipo:39
nulo
te lo envie a telegram pero ya no estabas ahi

**Comment by primitivorm** [comment]
que tienes en test.lat?

**Comment by otgo** [comment]
lo del telegram bot. Reinstale y todo y nada. Y pasé a c9 a verificar si era mi sistema y nada. la misma falla

**Comment by otgo** [comment]
https://github.com/primitivorm/latino/blob/master/ejemplos/26-telegram_bot.lat

**Comment by otgo** [comment]
```
# latino 22-teorema_pitagoras.lat
nodo_tipo:39
nulo
```

**Comment by primitivorm** [comment]
se corrige en version 0.6.0
