### ISSUE TITLE
variable indefinida - ubuntu 16.x.x

### ISSUE THREAD

**Issue by otgo** [lenguaje-latino/latino#39]
root@vps273405:~# latino elegir.lat
nodo_tipo:39
Error: Linea 3, 9: Variable "latino" indefinida

chatId = '-1001051061242' #chat latino
latino = "curl  -s 'https://api.telegram.org/bot" . TOKEN . "/sendMessage?chat_id=" . chatId . "&text=hola'"
sistema(latino)

root@modrank-latinoc-3753113:/home/ubuntu/workspace/latino/ejemplos# latino 15-funciones_mate.lat
nodo_tipo:39
nodo_tipo:39
nodo_tipo:39
nodo_tipo:39
nodo_tipo:39
nodo_tipo:39
nodo_tipo:39
nodo_tipo:39
nodo_tipo:39
nulo
root@modrank-latinoc-3753113:/home/ubuntu/workspace/latino/ejemplos# 

latino> sistema("echo dssd")
dssd
cfuncion <<<----- ¿¿¿??

**Comment by primitivorm** [comment]
se corrige en version 0.6.0
