### ISSUE TITLE
[Sugerencia] Cambiar "incluir" por "importar"

### ISSUE THREAD

**Issue by StunxFS** [lenguaje-latino/Latino#4]
### Sugerencia para Latino
Buenas! Quería darles una sugerencia, y es esta: cambiar la palabra "incluir" por "importar":

```c
// importar("modulo") <donde modulo es un archivo de código>
mod = importar("modulo")
poner(mod.variable)
```

¿Qué les parece la idea?

**Comment by MelvinG24** [comment]
Como @StunxFS,

Gracias por la sugerencia, aunque el comando incluir hace referencia al comando include de ANSI C. Se podría considerar incluir importar como una segunda opción, pero ya eso seria para una próxima version de Latino.

En visto de que este Issue fue para una sugerencia, lo voy a dar como terminado
