### ISSUE TITLE
Cambio de nombre

### ISSUE THREAD

**Issue by CestDiego** [lenguaje-latino/latino#43]
Gracias por esto, estoy pensando en hacer mi propio lenguaje de programación también. Y leer su código es de gran ayuda.

Tengo una recomendación,  y es que si se podría cambiarse el nombre a latin@ o latinx? Para ser inclusivo en género, hay mucho esfuerzo para que ambos géneros se puedan sentir incluidos en la profesión del desarrollo de software, y creo que hacer el nombre del lenguaje menos masculino podría ayudar en gran medida a que personas que no se identifiquen con el género masculino puedan identificarse.

**Comment by otgo** [comment]
@CestDiego Latino está protegido con derechos de copia. No puede ser copiado el código al 100 ya que este lenguaje fué escrito a derechos propios (primitivo) y no puede ser para uso financieros o propios. Te recomendaría mejor ayudarnos al proyecto y como vas ayudando podríamos ver si pasarte a que seas parte del proyecto ya que Programación Latino busca contribuidores en el código. Linda noche.

**Comment by otgo** [comment]
y el código a que te refieres con género? el nombre es referido al nombre de la programación y es general.

**Comment by kaliman111** [comment]
Es interesante, eres la tercer persona que desea cambiarle en nombre a "Latino", La primera fue por que decia que si usamos la palabra "Latino" los españoles no lo usaria, la segunda fue que "Latino" es una palabra que no tiene nada que ver con la programación, y ahora que es excluyente al genero femenino.

A este ritmo esperamos en un futuro más argumentos por los cuales deberíamos cambiar el nombre, y todos son bienvenidos, pero me gustaría hacerles una reflexion: miremos más alla del nombre, el motivo por el cual existe este lenguaje de progrmación en un idioma que es mio, que lo hablo desde chico, que no necesito mayor esfuerzo para entender una u otra palabra, lo que hay que preguntarse por que tardamos tanto en que este lenguaje existiera, por que otros intentos de hacerlos no fueron más alla, por que si hay tantas universidadds en Latinoamérica con miles de egresados anualmente como ingenieros informáticos solo hasta ahora existe "Latino" o con cualquier nombre (con sus [exepciones](http://lenguaje-latino.org/comunidad/)) porque?

Hay muchas respuestas a esa pregunta y todas seguramente seran validas, y podriamos lanzarnos en debates que se alejan del objetivo mismo que cada uno de nosotros tenemos, y si estas leyendo estas lineas es que de una u otra manera estas interesando en el mundo de la programación, ya sea como aficionado o profesional, talvez tengas algun proyecto en mente como @CestDiego que inicio este tema y desea hacer su propio lenguaje, a ti lector te hago la invitación a que: crees un proyecto o te unas a uno que existe, esto es como un equipo de futbol, hay arqueros, defensas, delanteros, entrenadores, ayudantes, hinchas, y sin otro equipo no hay campeonato, en los proyectos es igual, hace falta programadores, diseñadores graficos, editores de video, locutores, articulistas, redactores, correctores de ortografía, gente que haga pruebas, y mucha mucha gente que no tenga nada que ver con el mundo de la programación para que opine y de su punto de vista y asi como en el futbol, todos con un mismo pensamiento en el cabeza, que su equipo gane el campeonato, y en la programación es que el proyecto salga adelante.

Y si "Latino" te abre los ojos, te sirve de inspiración, te ayuda a ver que es posible, uno de nuestros objetivos esta cumplido,

**Comment by robincoello** [comment]
Es interesante, eres la tercer persona que desea cambiarle en nombre a "Latino", La primera fue por que decia que si usamos la palabra "Latino" los españoles no lo usaria, la segunda fue que "Latino" es una palabra que no tiene nada que ver con la programación, y ahora que es excluyente al genero femenino.

A este ritmo esperamos en un futuro más argumentos por los cuales deberíamos cambiar el nombre, y todos son bienvenidos, pero me gustaría hacerles una reflexion: miremos más alla del nombre, el motivo por el cual existe este lenguaje de progrmación en un idioma que es mio, que lo hablo desde chico, que no necesito mayor esfuerzo para entender una u otra palabra, lo que hay que preguntarse por que tardamos tanto en que este lenguaje existiera, por que otros intentos de hacerlos no fueron más alla, por que si hay tantas universidadds en Latinoamérica con miles de egresados anualmente como ingenieros informáticos solo hasta ahora existe "Latino" o con cualquier nombre (con sus [exepciones](http://lenguaje-latino.org/comunidad/)) porque?

Hay muchas respuestas a esa pregunta y todas seguramente seran validas, y podriamos lanzarnos en debates que se alejan del objetivo mismo que cada uno de nosotros tenemos, y si estas leyendo estas lineas es que de una u otra manera estas interesando en el mundo de la programación, ya sea como aficionado o profesional, talvez tengas algun proyecto en mente como @CestDiego que inicio este tema y desea hacer su propio lenguaje, a ti lector te hago la invitación a que: crees un proyecto o te unas a uno que existe, esto es como un equipo de futbol, hay arqueros, defensas, delanteros, entrenadores, ayudantes, hinchas, y sin otro equipo no hay campeonato, en los proyectos es igual, hace falta programadores, diseñadores graficos, editores de video, locutores, articulistas, redactores, correctores de ortografía, gente que haga pruebas, y mucha mucha gente que no tenga nada que ver con el mundo de la programación para que opine y de su punto de vista y asi como en el futbol, todos con un mismo pensamiento en el cabeza, que su equipo gane el campeonato, y en la programación es que el proyecto salga adelante.

Y si "Latino" te abre los ojos, te sirve de inspiración, te ayuda a ver que es posible, uno de nuestros objetivos esta cumplido,

**Comment by otgo** [comment]
Bien dicho @robincoello . Latino no hace referencia a un género en particular. La gente usa aquí la palabra como "yo hablo Latino", "Mi lenguaje es español Latino" lo cúal no es referente al tipo de género de cada persona. Cambiarle el nombre, lo veo de una manera un poco extraña por ahora y se necesitarán aún más argumentos para que dicho cambio de efectivo. ¿Por qué no unirse? Un proyecto unidos es un mejor proyecto y bien hecho, he creado un script en Latino para que hagan un test de aquello, cada quién podrá aprender la programación fácilmente y sabrá que se puede usar de muchas maneras: Queda en tí cúal sea tu idea.

**Comment by robincoello** [comment]
> he creado un script en Latino para que hagan un test de aquello
> @jarriztg Donde lo puedo ver

**Comment by otgo** [comment]
https://github.com/jarriztg/LatinoBot

**Comment by CestDiego** [comment]
Muchas gracias por sus prontas respuestas. Quisiera aclarar que no planeaba
contribuir a 'latino'  primero,  siento que mi nivel de C y de como crear
lenguajes de programación es muy pequeño. Estoy viendo cursos en internet
de la. Universidad de Brown para aprender este tipo de cosas. Y estoy
haciendo mi lenguaje de programación solo para aprender. Y creo que será
muy diferente a latino. En que será más como un lisp más que como un C.
Aprecio su invitación a colaborar en el proyecto. Y si es que en algún
momento siento que ya entiendo los lenguajes de programación lo
suficientemente como para añadir tail call optimization a Latino pues
estaría feliz de hacerlo.

Muchas gracias,
Diego

**Comment by robincoello** [comment]
@jarriztg : sobre lo que dices 

> Latino está protegido con derechos de copia. No puede ser copiado el código al 100 ya que este lenguaje fué escrito a derechos propios (primitivo) y no puede ser para uso financieros o propios. 

Debo aclarar que la [licencia](https://github.com/primitivorm/latino/blob/master/LICENCIA.txt) bajo la cual esta "Latino " dice: 

Se concede permiso, de forma gratuita, a cualquier persona que obtenga una copia
de este software y archivos de documentacion asociados (el "Software"), para hacer frente
el Software sin restriccion, incluyendo sin limitacion, los derechos
para usar, copiar, modificar, fusionar, publicar, distribuir, sublicenciar y / o vender
las copias del Software y permitir a las personas a las que el Software es
amueblado para hacerlo, con sujecion a las siguientes condiciones:

El aviso de copyright anterior y este aviso de permiso se incluiran en
todas las copias o partes sustanciales del Software.

EL SOFTWARE SE PROPORCIONA "TAL CUAL", SIN GARANTIA DE NINGUN TIPO, EXPRESA O
IMPLICITAS, INCLUYENDO PERO NO LIMITADO A LAS GARANTIAS DE COMERCIALIZACION,
IDONEIDAD PARA UN PROPOSITO PARTICULAR Y NO INFRACCION. EN NINGUN CASO EL
AUTORES O TITULARES DEL COPYRIGHT SERAN RESPONSABLES POR NINGUN RECLAMO, DAÑO U OTRA
RESPONSABILIDAD, YA SEA EN UNA ACCION DE CONTRATO, AGRAVIO O CUALQUIER OTRA FORMA, DERIVADOS DE,
DE O EN RELACION CON EL SOFTWARE O EL USO U OTROS TRATOS EN
EL SOFTWARE.

**Comment by CestDiego** [comment]
Si pues eso me pareci'o raro, porque la licencia del MIT es la menos permisivas de todas, así que cualquier persona podría utilizarlos al 100 para cualquier propósito, incluso comercial por un lado (incluyendo el código fuente sólo de latino y tmb incluyendo su licencia), o hacerlo más restrictivo con una licencia GPL para que ya no pueda ser usado comercialmente sin exponer el código fuente
