### ISSUE TITLE
texto[1+1]

### ISSUE THREAD

**Issue by robincoello** [lenguaje-latino/latino#45]
texto = 'Latino'
escribir(texto[1+1])

Error: Linea 2, 17: syntax error, unexpected '+', expecting ']'

**Comment by primitivorm** [comment]
hola @robincoello, no se permiten expresiones entre "[" y "]":

texto = 'Latino'
escribir(texto[2])   #esto te deberia de funcionar

**Comment by robincoello** [comment]
ok
