### ISSUE TITLE
 es_numerico()

### ISSUE THREAD

**Issue by robincoello** [lenguaje-latino/latino#46]
n = "1abcdfgytypoipiklkjlmkj"
si(es_numerico(n))
    escribir("Es numero")
sino
    escribir("No es")
fin
// da
Es numero

Esta funcion deberia comparar si todos los caracteres de la cadena son numeros arrojar verdadero si hay un solo que no es numero deberia dar falso

**Comment by primitivorm** [comment]
@robincoello 

Listo, ya esta funcionando por favor instala la version 0.8.1 de latino

Saludos
