### ISSUE TITLE
incluir()

### ISSUE THREAD

**Issue by robincoello** [lenguaje-latino/latino#52]
si tengo un error en un archivo a.lat el cual esta incluido en otro b.lat y ejecuto el b.lat me sale el error 

[user@localhost latino-Markdown]$ latino b.lat 
Error: Linea 1, 11: syntax error, unexpected $end, expecting ')'
Erreur de segmentation (core dumped)

Pero no me dice si el error esta en a.lat o b.lat y un huevo si tengo varias incluciones jejeje

**Comment by primitivorm** [comment]
corregido en version 0.8.11
