### ISSUE TITLE
a = leer_lineas('datos.lat')

### ISSUE THREAD

**Issue by robincoello** [lenguaje-latino/latino#57]
datos.lat tiene 
a
b
c
d
f
index.lat
a = leer_lineas('datos.lat')
escribir(a)

Resultado 
["a", "b", "c", "d"]

Asi que no me lee la ultima linea, pero si le agrego una linea vacia al fichero datos.lat, si me entrega todos los datos,

**Comment by primitivorm** [comment]
Puedes hacer git pull por favor y compilar nuevamente

A mi no me da ese caso:
$cat datos.lat
a
b
c
d
f
./latino index.lat
["a", "b", "c", "d", "f"]
