### ISSUE TITLE
separar

### ISSUE THREAD

**Issue by robincoello** [lenguaje-latino/latino#58]
si tengo datos.lat
una
dos
tres cuatro
 y en index.lat ejecuto esto: 
frase = leer_archivo('datos.lat')
a = separar(frase)
escribir(longitud(a))
escribir(a)
------Resultado------------------------------------
2
["una
dos
## tres", "cuatr"]

Deberia tomar en cuenta el salto de linea para la separacion de las palabras?
la ultima letra de la ultima palabra desaparecio

**Comment by primitivorm** [comment]
hola en este caso cuando no le pasas valor a la funcion separar por default lo separa por espacios, y un espacio " " no es lo mismo que salto de linea "\n". Si se deja la funcion que separe por espacios y salto de linea ya no le estamos dejando la opcion al usuario de elegir. 
Para obtener el resultado que deseas primero obtener las lineas del archivo con la funcion leer_lineas y luego por cada linea separas por espacios.

Aqui el codigo:
lineas = leer_lineas('datos.lat')
palabras = []
desde (i=0; i<lineas->longitud(); i++)
  palabras->extender(separar(lineas[i]))
fin
escribir(palabras)
#salida:
["una", "dos", "tres", "cuatro"]

Hice el ejemplo que mencionas y no le quita la "o" al final del "cuatro":
$ cat datos.lat 
una
dos
tres cuatro

$ cat index.lat 
frase = leer_archivo('datos.lat')
a = separar(frase)
escribir(longitud(a))
escribir(a)

$ ./latino index.lat 
2
["una
dos
tres", "cuatro"]
