### ISSUE TITLE
si creo dos fuciones con el mismo nombre no da error

### ISSUE THREAD

**Issue by robincoello** [lenguaje-latino/latino#63]
funcion max()

fin

funcion max()

fin

**Comment by otgo** [comment]
En cualquier lenguaje de programación no marca error ni debería, si no que se le asigna de nuevo la función que dará ese script, por ejemplo:

Tengo mi función llamada "seleccionar"

El código es el siguiente:

```
funcion seleccionar(a)
     imprimir("Haz seleccionado la letra ".a)
fin
```

Si en cualquier momento quiero reasignar función para tener más o menos parametros tendré que volverla a hacer:

```
funcion seleccionar(a, b)
     imprimir("Haz seleccionado la letra ".a." y la letra ".b)
fin
```

Quedandó si ponemos la primera función el retorno así:

``` bash
# función = seleccionar()
Haz seleccionado la letra x
# Reasignamos la función seleccionar()
Haz seleccionado la letra x y le letra x
```

**Comment by otgo** [comment]
dejaré un ejemplo en la sección de ejemplos
