### ISSUE TITLE
reconfiguracion de hacer

### ISSUE THREAD

**Issue by robincoello** [lenguaje-latino/latino#64]
Me parece mas adecuado asi

nombre = ''
i = 1
hacer
    nombre .= texto[i]
    i++
mientras (i < 10)
escribir(nombre)

osea la palabra 'mientras' en lugar de la 'cuando' tiene mas sentido en el conexto

**Comment by primitivorm** [comment]
@robincoello, por limitantes de bison no se puede hacer ese cambio, lo mas que se podria hacer es cambiarlo por la forma repeat:

i = 0
repetir
  escribir(i)
  i++
hasta i < 10

En lua existe asi:
-- https://www.lua.org/pil/4.3.3.html
-- print the first non-empty line
    repeat
      line = os.read()
    until line ~= ""
    print(line)

**Comment by primitivorm** [comment]
Se corrige en version Latino 0.9.0
ver ejemplos/07-repetir.lat
