### ISSUE TITLE
es_numerico

### ISSUE THREAD

**Issue by robincoello** [lenguaje-latino/latino#65]
n = falso
si(es_numerico(n))
    escribir('Si')
sino
    escribir('No')
fin
da 
 Error: Linea 3, 14: El parametro debe de ser una cadena en archivo '/var/www/html/latino-Markdown/d.lat'.

deberia poder recibir cualquier tipo de parametro en vista que va a verificar si es numero

**Comment by otgo** [comment]
@robincoello Intentaste con un valor que no sea tipo booleano?

**Comment by robincoello** [comment]
otro que no sea boleano ok

**Comment by otgo** [comment]
@robincoello El error que dice más o menos es que el valor tiene que ser de tipo cadena ó númerico

**Comment by otgo** [comment]
@jarriztg Puedes ponerlo como:
a = verdadero
b = 2
si (a) && (es_numerico(b))
     imprimir(b." es un valor númerico")
sino
    imprimir(b. "no es un valor númerico")
fin

**Comment by robincoello** [comment]
asi es, deberia poder recibir todo tipo de dato para analizarlo, y dar resultado verdadero si es numero falso si no lo es

**Comment by otgo** [comment]
@robincoello Si tienes razón, igual y podrias usar la otra forma de a mientras

**Comment by primitivorm** [comment]
@robincoello la función es_numerico es para validar si un texto (cadena) es numérico es decir que solo contiene números ya sean enteros o decimales. Si le pasas otro tipo de dato te dará error, los errores sirven para que el programador cambien si lógica de lo que está validando esta mal.
