### ISSUE TITLE
esta_vacia

### ISSUE THREAD

**Issue by robincoello** [lenguaje-latino/latino#66]
n = falso
si(esta_vacia(n))
    escribir('Si')
sino
    escribir('No')
fin
da error 
 Error: Linea 3, 15: El parametro debe de ser una cadena en archivo '/var/www/html/latino-Markdown/d.lat'.
 en este caso la 'n' vale falso asi que 'n' no esta vacia

**Comment by primitivorm** [comment]
@robincoello la función es para validar si una cadena esta vacia, no para tipos de datos booleanos, una variable tipo booleano siempre va a ser verdadero o falso.

**Comment by robincoello** [comment]
**esta_vacia()** hace pensar que evalua una variable, ahora una variable puede ser de cualquier tipo, si esta variable tiene un valor asigando esta llena caso contrario esta vacia, 
n = '' > esta vacia 
n = falso > no esta vacia
n = nulo > no esta vacia
n = 'Hola' no esta vacia

**Comment by primitivorm** [comment]
en latino no pueden crearse variable vacias, todas deben de tener un valor asignado al momento de crearlas.
si pones esto en latino, te mandara error:
variable
otra_variable
x
y

**Comment by robincoello** [comment]
y si pones 
n= '' 
Esta vacia  esta llena?

**Comment by otgo** [comment]
@robincoello Esa queda inválida
si n
 #código
fin

Y puedes ponerlo como si falta valor

si ! n
  #codigo
fin

Las vacías y valores falsos los toma como falsos (a ambos)
