### ISSUE TITLE
funcion verificar_año(a)  

### ISSUE THREAD

**Issue by robincoello** [lenguaje-latino/latino#82]
Error: Linea 3, 22: syntax error, unexpected IDENTIFICADOR, expecting '(' en archivo 'inicio.lat'.

**Comment by primitivorm** [comment]
Por favor revisa los ejemplos/modulo.lat y ejemplos/33-incluir.lat. Ahora debes de asignar el valor de incluir a una variable:
mod = incluir("modulo")
