### ISSUE TITLE
error al incluir 

### ISSUE THREAD

**Issue by robincoello** [lenguaje-latino/latino#83]
tengo dos ficheros
index.lat
funciones.lat
-------------------
en index
incluir("funciones")
escribir('Dame un año')
a = leer()
verificar_a(a)
***********
en funciones
funcion verificar_a(a)    
    mientras ( a == 0 )
        escribir("Debe ser diferente a cero")
        a = leer()
    fin
fin 
---------------------------
al ejecutar index 
[roencosa@localhost latino-ejemplos]$ latino inicio.lat 
Dame un año
2016
 Error: Linea 7, 1: Variable "verificar_a" indefinida en archivo '/home/roencosa/latino-ejemplos/funciones.lat'.
[roencosa@localhost latino-ejemplos]$

**Comment by otgo** [comment]
Sip, acabo de verificar y no funciona sin el módulo declarado

**Comment by primitivorm** [comment]
Por favor revisa los ejemplos/modulo.lat y ejemplos/33-incluir.lat. Ahora debes de asignar el valor de incluir a una variable:
`mod = incluir("modulo")`

```
#archivo modulo.lat
variable = 23
funcion sumatoria(a, b)
  retorno (a + b)
fin
//se deben de regresar las funciones y variables que se quieran exponer del modulo
retornar {"variable" : variable,
"sumatoria" : sumatoria}
```

```
#archivo 33-incluir.lat
mod = incluir("modulo") //ahora modulo es una funcion que se puede asignar a una variable
r = mod->sumatoria(2, 3)
escribir(r)
escribir(mod->variable)
```

**Comment by primitivorm** [comment]
se corrige funcion incluir para admitir ambas versiones, actualizar con $git pull

```
#archivo modulo.lat
variable = 23
funcion sumatoria(a, b)
  retorno (a + b)
fin
//se deben de regresar las funciones y variables que se quieran exponer del modulo
retornar {"variable" : variable,
"sumatoria" : sumatoria}
```

```
#test
incluir("modulo")
escribir(sumatoria(1,2)) #no da error


mod = incluir("modulo")

r = mod->sumatoria(1,2)
escribir(r)  
escribir(sumatoria(1,2)) #no da error
```

**Comment by robincoello** [comment]
Voila una buena idea !
