### ISSUE TITLE
mientras dentro de una funcion 

### ISSUE THREAD

**Issue by robincoello** [lenguaje-latino/latino#84]
si pongo esto en un fichero y ejecuto me repetira mientras no le de un valor y este sea diferente a cero, 
    mientras ( a == 0 || a == nulo )
        escribir("Debe ser diferente a cero")
        a = leer()
    fin

Pero, si le pongo esto en una funcion 

funcion verificar_a(a)    
    mientras ( a == 0  || a == nulo )
        escribir("Debe ser diferente a cero")
        a = leer()
    fin
fin 
y despues llamo la funcion 
escribir('Dame un año')
a = leer()
verificar_a(a)

Solo me ejecuta una sola vez,

**Comment by primitivorm** [comment]
Puedes verificar con la version 0.9.0 de latino por favor

```
funcion verificar_a(a)
  mientras ( a == 0 || a == nulo )
    escribir("Debe ser diferente a cero")
    a = leer()
  fin
fin

escribir('Dame un año')
a = leer()
verificar_a(a)
```
