### ISSUE TITLE
extructura > error 

### ISSUE THREAD

**Issue by robincoello** [lenguaje-latino/latino#85]
// supongo q no esta implemntada, si es el caso talvez se pueda analizar para implemtar, 
// o es un error ?

Me da este error: 
 Error: Linea 6, 9: syntax error, unexpected CASO en archivo 'd.lat'.

escribir('Dame un mes')
m = leer()    
elegir(m)
        caso 1: // meses de 31 dias
        caso 3:
        caso 5:
        caso 7:
        caso 10:
        caso 12:
            escribir("mes de 31 dias")
        caso 4:// meses de 30 dias
        caso 6:
        caso 9:
        caso 11:
            escribir("mes de 30 dias ")
        caso 2: //feb que es de 28 y 29 dias 
            escribir("Feb, de 28 o 29 dias")
    fin

**Comment by robincoello** [comment]
quiero que en estos casos 
caso 1: // meses de 31 dias
caso 3:
caso 5:
caso 7:
caso 10:
caso 12:
escribir("mes de 31 dias")

se ejecuta el codigo x
y asi en los otros caso

**Comment by primitivorm** [comment]
No se tiene esta funcionalidad en latino, se debe de incluir codigo por cada caso:
Para este ejemplo podrias utilizar "si" "osi" se reduciria mucho tu codigo:

```
escribir("Dame un mes")
mes = leer()
si mes ==1 || mes ==3 || mes == 5 || mes == 7 || mes == 10 || mes == 12
  escribir("mes de 31 días")
osi mes == 4 || mes == 6 || mes == 8 || mes == 9 || mes == 11
  escribir("mes de 30 días")
sino
  escribir("mes de 28 días")
fin
```
