### ISSUE TITLE
version 0.9.0

### ISSUE THREAD

**Issue by robincoello** [lenguaje-latino/latino#86]
contenido = "prueba de escritura de archivo \n desde Latino"
escribir_archivo("prueba.txt", contenido)
 Error: Linea 2, 1: Variable "escribir_archivo" indefinida en archivo 'd.lat'.
[user@localhost latino-ejemplos]$

**Comment by primitivorm** [comment]
Con la creación de módulos esa función quedó de la siguiente manera.

archivo->escribir("prueba.txt", contenido)

Por favor revisa los ejemplos

**Comment by robincoello** [comment]
Yo vi aca para usarlo [☹]

https://github.com/primitivorm/latino/blob/master/ejemplos/10-funciones.lat

**Comment by primitivorm** [comment]
No entiendo tu duda Robinsón, podrías ser más específico

"Yo vi aca para usarlo [☹]"
