### ISSUE TITLE
Errores encontrados en cadena

### ISSUE THREAD

**Issue by otgo** [lenguaje-latino/latino#89]
1. cadena->invertir() // error core
2. cadena->es_alfanumerico() // no detecta que sea alfanúmerico
3- cadena->ejecutar() // probé con escribir y dió error
4- cadena->indice // error core
5- cadena->reemplazar() // simplemente no reemplaza

**Comment by primitivorm** [comment]
Sería de gran ayuda que pusieras un ejemplo de cada uno de los casos para analizar qué está faltando y esta mal, por lo pronto revisare que está pasando muchas gracias :)

**Comment by primitivorm** [comment]
se corrige funcion invertir y se cambia funcion es_alfanumerico por es_alfa
Las demas funciones corren OK.
ejemplos:

```
str = "hola mundo"
escribir(cadena->invertir(str))
escribir(cadena->es_alfa(str))  #da falso porque espacio no es alfanumerico
cadena->ejecutar("escribir('hola desde una cadena')")
pos = cadena->indice(str, "mundo")
escribir("'hola' esta en la posicion: " . pos)
#crea una nueva cadena, no reemplaza la cadena anterior
nueva = cadena->reemplazar(str, "mundo", "latinos")
escribir(nueva)
escribir(str) #cadena original
```

hacer git pull para actualizar version...
