### ISSUE TITLE
Añadir instruciones de installación para Windows

### ISSUE THREAD

**Issue by rootmeanclaire** [lenguaje-latino/latino#91]
Los que quieren usar latino para educación probablemente no usan Linux.

**Comment by otgo** [comment]
@FracturedRetina No es nada dificil, solamente es descargar el exe en releases e instalarlo, y claro que se puede usar Latino en Linux, y yo lo recomendaría ya que corre mejor en Linux y su perfomance es mucho mayor.

**Comment by primitivorm** [comment]
Las instrucciones estan en el README.md, se instala como cualquier otra aplicacion en Windows

###Instalar en Windows

    1. Descargue el instalador de la última version de https://github.com/primitivorm/latino/releases
    2. Descompima el archivo zip
    3. Ejecute el instalador
