### ISSUE TITLE
error al incluir con retorno

### ISSUE THREAD

**Issue by otgo** [lenguaje-latino/latino#92]
test.lat:
```
test = "hola"
funcion v(a)
  imprimir("A es ".a." y test es ".test)
fin
retorno {
        "v": v
}
```

x.lat:
```
vv = incluir("test")

vv->v("vd")
```

ERROR: 
Error: Linea 4, 36: Variable "test" indefinida en archivo '/home/jarriz/test.lat'.

**Comment by primitivorm** [comment]
esto es por que test es local al modulo `test.lat` como estas ejecutando la funcion  `v` desde fuera tendras que retornarla para que se vuelva global.
```
test = "hola"
funcion v(a)
  imprimir("A es ".a." y test es ".test)
fin
retorno {
        "v": v,
        "test" : test     #<-- agrega esta linea a tu codigo
}
```
