### ISSUE TITLE
recomendación para listas

### ISSUE THREAD

**Issue by otgo** [lenguaje-latino/latino#94]
```bash
a = []
a[1] = "hola" # añade el elemento "hola" a la lista "a" en la posición 1
imprimir(a[1])
```

**Comment by jordanclic** [comment]
**Listas**

> `frutas = ["naranja", "melon", "sandia"]
> calificaciones = [10, 9, 8, 5]`

**Palabras clave**

> `promedios = {"juan" : 9.5, 
>            "lola" : 8.3, 
>            "victor" : 9.2, 
>            "pedro" : 7.1 }`
> `promedios.insertar(promedios, jordan : 6.5, 5)`
> `escribir(promedios{3} . frutas[2, 1])`
