### ISSUE TITLE
convierte listas a cadenas en bucle

### ISSUE THREAD

**Issue by otgo** [lenguaje-latino/latino#95]
```x=0
mientras (x<lista->longitud(config->plugins))
	res = incluir("plugins/".config->plugins[x])
	imprimir(tipo(res))
	com = res[lista->longitud(res)-1]
	desde (i=0; i<(lista->longitud(res)-1); i++)
	matches = cadena->match(msg->texto, res[i])
	si convertir->cadena(com->subproceso) == "funcion"
		com->subproceso()
	fin
	si matches
 		si convertir->cadena(com->accion) == "funcion"
			com->accion()
		fin
	fin
fin
x++
fin
fin
```

logs:
Confirmación enviada a 189041244.
Bot @BetaLatinoBot
lista <-- indica que es lista
lista <-- indica que es lista
cadena  <-- ahora indica que es cadena??
 Error: Linea 67, 28: El parametro debe de ser una lista en archivo '/home/jarriz/BotGram/plugins/test.lat'.

**Comment by primitivorm** [comment]
Puedes poner que contiene tu variable config->plugins y que trae tu valor `res`
imprimir(tipo(res))
imprimir(res)   <-- agrega esta linea a tu codigo para debuguear el valor
